version: "3"

services:
  postgres-db:
    container_name: postgres
    image: "postgres:alpine"
    ports:
      - "5432:5432"
    env_file:
      - database.env

volumes:
  postgres-data:
    driver: local
